FROM meliuz/node:10.15

ENV NGINX_DIR=/etc/nginx
ENV NGINX_PID_FILE=/run/nginx.pid

ARG nginx_config
ARG S3_ACCESS_KEY_ID
ARG S3_SECRET_ACCESS_KEY
ARG S3_BUCKET
ARG PUB_BFF_CUSTOMER_ADDRESS
ARG PUB_DOMAIN
ARG PUB_SENTRY_DSN
ARG PUB_APPLE_ITUNES_ID
ARG PUB_IR_VERIFICATION_TOKEN
ARG PUB_LOMADEE_VERIFICATION
ARG PUB_FACEBOOK_ID
ARG PUB_GA_ID
ARG PUB_GTM_ID
ARG PUB_AD_MANAGER_ID
ARG PUB_RECAPTCHA_KEY
ARG PUB_CLIENT_ID
ARG PUB_CLIENT_SECRET
ARG PUB_STATIC_ASSETS_URL
ARG PUB_ONESIGNAL_APP_ID
ARG GIT_COMMIT_HASH
ARG PROJECT_ENVIRONMENT=development
ARG PUB_APPS_FLYER_SMART_BANNER_KEY

# Default: development values
ENV S3_ACCESS_KEY_ID ${S3_ACCESS_KEY_ID}
ENV S3_SECRET_ACCESS_KEY ${S3_SECRET_ACCESS_KEY}
ENV S3_BUCKET ${S3_BUCKET}
ENV PUB_BUCKET_ADDRESS ${PUB_BUCKET_ADDRESS:-https://staticz.com.br}
ENV PUB_APPS_FLYER_SMART_BANNER_KEY ${PUB_APPS_FLYER_SMART_BANNER_KEY}
ENV PUB_BFF_CUSTOMER_ADDRESS ${PUB_BFF_CUSTOMER_ADDRESS:-https://api-customer.meliuz-dev.com.br}
ENV PUB_DOMAIN ${PUB_DOMAIN:-https://www.meliuz-dev.com.br}
ENV PUB_SENTRY_DSN ${PUB_SENTRY_DSN}
ENV PUB_APPLE_ITUNES_ID ${PUB_APPLE_ITUNES_ID:-993672585}
ENV PUB_IR_VERIFICATION_TOKEN ${PUB_IR_VERIFICATION_TOKEN:-500208474}
ENV PUB_LOMADEE_VERIFICATION ${PUB_LOMADEE_VERIFICATION:-22496346}
ENV PUB_FACEBOOK_ID ${PUB_FACEBOOK_ID:-244006035702547}
ENV PUB_GA_ID ${PUB_GA_ID}
ENV PUB_GTM_ID ${PUB_GTM_ID}
ENV PUB_AD_MANAGER_ID ${PUB_AD_MANAGER_ID:-27686749}
ENV PUB_RECAPTCHA_KEY ${PUB_RECAPTCHA_KEY}
ENV PUB_CLIENT_ID ${PUB_CLIENT_ID}
ENV PUB_CLIENT_SECRET ${PUB_CLIENT_SECRET}
ENV PUB_STATIC_ASSETS_URL ${PUB_STATIC_ASSETS_URL}
ENV PUB_ONESIGNAL_APP_ID ${PUB_ONESIGNAL_APP_ID}
ENV PROJECT_ENVIRONMENT ${PROJECT_ENVIRONMENT}
ENV GIT_COMMIT_HASH ${GIT_COMMIT_HASH}

USER root

RUN apt-get update \
    && apt-get install -y -q --no-install-recommends nginx supervisor \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY nginx/nginx.conf ${NGINX_DIR}/
COPY ${nginx_config} ${NGINX_DIR}/sites-enabled/
COPY ./resources/ssl/ ${NGINX_DIR}/conf.d

RUN rm -rf ${NGINX_DIR}/sites-available/default ${NGINX_DIR}/sites-enabled/default
RUN touch ${NGINX_PID_FILE}
RUN chown -R ${USER_NAME}:${USER_NAME} ${NGINX_DIR} /var/log/nginx /var/lib/nginx ${NGINX_PID_FILE}

USER ${USER_NAME}

COPY --chown=app:app package*.json ./
RUN npm install --loglevel=warn && mv package-lock.json /tmp/package-lock.json

COPY --chown=app:app . ./

RUN npm run build
RUN find ./dist -type f -name "*" -exec gzip --keep {} \;

RUN node scripts/s3-uploader.js
